# 탑마케팅 플랫폼 도커 컴포즈 백업 파일
# 이 파일은 복구 시 참조용으로 사용됩니다.
# 실제 운영 환경에 맞게 수정하여 사용하세요.

version: '3.8'

services:
  # 웹 서버 (Nginx + PHP-FPM)
  web:
    image: nginx:alpine
    container_name: topmkt_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./docs:/var/www/html/docs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/assets/uploads:/var/www/html/public/assets/uploads
    depends_on:
      - php
      - db
    networks:
      - topmkt_network
    restart: unless-stopped

  # PHP-FPM
  php:
    image: php:8.1-fpm
    container_name: topmkt_php
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_HOST=db
      - DB_NAME=topmkt
      - DB_USERNAME=topmkt_user
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - topmkt_network
    restart: unless-stopped

  # 데이터베이스 (MariaDB)
  db:
    image: mariadb:10.6
    container_name: topmkt_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: topmkt
      MYSQL_USER: topmkt_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/backup:/backup
    ports:
      - "3306:3306"
    networks:
      - topmkt_network
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis (캐싱용, 선택사항)
  redis:
    image: redis:7-alpine
    container_name: topmkt_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - topmkt_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # 백업 컨테이너 (정기 백업용)
  backup:
    image: alpine:latest
    container_name: topmkt_backup
    volumes:
      - db_data:/backup/db_data:ro
      - ./public/assets/uploads:/backup/uploads:ro
      - ./backup:/backup/output
    environment:
      - DB_HOST=db
      - DB_NAME=topmkt
      - DB_USER=topmkt_user
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - topmkt_network
    restart: "no"
    entrypoint: /bin/sh
    command: -c "echo 'Backup container ready. Run manually for backups.'"

# 볼륨 정의
volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

# 네트워크 정의
networks:
  topmkt_network:
    driver: bridge