echo "/* 탑마케팅 레이아웃 컴포넌트 */\n";
echo "\n";
echo "/* 레이아웃 */\n";
echo ".container {\n";
echo "    max-width: 1200px;\n";
echo "    margin: 0 auto;\n";
echo "    padding: 0 20px;\n";
echo "}\n";
echo "\n";
echo "/* 개선된 헤더 스타일 */\n";
echo ".main-header {\n";
echo "    background: linear-gradient(to right, #1E3A8A, #3949ab);\n";
echo "    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n";
echo "    padding: 0;\n";
echo "    position: sticky;\n";
echo "    top: 0;\n";
echo "    z-index: 1000;\n";
echo "}\n";
echo "\n";
echo ".main-header .container {\n";
echo "    display: flex;\n";
echo "    justify-content: space-between;\n";
echo "    align-items: center;\n";
echo "    padding: 15px 20px;\n";
echo "}\n";
echo "\n";
echo ".header-left {\n";
echo "    display: flex;\n";
echo "    align-items: center;\n";
echo "}\n";
echo "\n";
echo ".logo {\n";
echo "    margin: 0;\n";
echo "    padding: 0;\n";
echo "}\n";
echo "\n";
echo ".logo a {\n";
echo "    display: flex;\n";
echo "    align-items: center;\n";
echo "    font-size: 24px;\n";
echo "    font-weight: 700;\n";
echo "    color: #fff;\n";
echo "    transition: all 0.3s ease;\n";
echo "}\n";
echo "\n";
echo ".logo a:hover {\n";
echo "    text-decoration: none;\n";
echo "    transform: scale(1.05);\n";
echo "}\n";
echo "\n";
echo ".logo img {\n";
echo "    height: 36px;\n";
echo "    margin-right: 10px;\n";
echo "}\n";
echo "\n";
echo ".main-nav {\n";
echo "    margin-left: 30px;\n";
echo "}\n";
echo "\n";
echo ".main-nav ul {\n";
echo "    display: flex;\n";
echo "    gap: 5px;\n";
echo "}\n";
echo "\n";
echo ".main-nav li {\n";
echo "    position: relative;\n";
echo "}\n";
echo "\n";
echo ".main-nav a,\n";
echo ".main-nav button {\n";
echo "    display: block;\n";
echo "    padding: 10px 15px;\n";
echo "    color: rgba(255, 255, 255, 0.9);\n";
echo "    font-weight: 500;\n";
echo "    font-size: 16px;\n";
echo "    border-radius: 4px;\n";
echo "    transition: all 0.3s ease;\n";
echo "}\n";
echo "\n";
echo ".main-nav a:hover,\n";
echo ".main-nav button:hover {\n";
echo "    background-color: rgba(255, 255, 255, 0.1);\n";
echo "    color: #fff;\n";
echo "    text-decoration: none;\n";
echo "}\n";
echo "\n";
echo ".main-nav a.active {\n";
echo "    background-color: rgba(255, 255, 255, 0.2);\n";
echo "    color: #fff;\n";
echo "}\n";
echo "\n";
echo "/* 특별 메뉴 스타일링 (신청 관리 등) */\n";
echo ".main-nav .special-menu {\n";
echo "    background: linear-gradient(135deg, #43e97b 0%, #38f9d7 100%) !important;\n";
echo "    color: #fff !important;\n";
echo "    font-weight: 600;\n";
echo "    box-shadow: 0 2px 20px rgba(67, 233, 123, 0.3);\n";
echo "    border: 2px solid rgba(255, 255, 255, 0.3);\n";
echo "    position: relative;\n";
echo "    overflow: hidden;\n";
echo "}\n";
echo "\n";
echo ".main-nav .special-menu::before {\n";
echo "    content: '';\n";
echo "    position: absolute;\n";
echo "    top: 0;\n";
echo "    left: -100%;\n";
echo "    width: 100%;\n";
echo "    height: 100%;\n";
echo "    background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\n";
echo "    transition: left 0.5s;\n";
echo "}\n";
echo "\n";
echo ".main-nav .special-menu:hover::before {\n";
echo "    left: 100%;\n";
echo "}\n";
echo "\n";
echo "/* 모바일에서 특별 메뉴 스타일 */\n";
echo "@media (max-width: 768px) {\n";
echo "    .main-nav .special-menu {\n";
echo "        padding: 8px 12px;\n";
echo "        font-size: 14px;\n";
echo "        margin: 2px;\n";
echo "    }\n";
echo "}\n";
